name: sa_lego_cloud_functions_lego
description: "lego is all you need"
#publish_to: 'none'
repository: https://github.com/flutter-lego/sa_lego_cloud_functions_lego

version: 1.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: #@add
  gap: #@add
  june_flow_util: #@add
  styled_widget: #@add
  modal_bottom_sheet: #@add
  keyboard_attachable: #@add
  flutter_zoom_drawer: #@add
  flutter_screenutil:
  bot_toast:
  cloud_functions: #@add
  firebase_core:
  firebase_auth:
  google_sign_in:
  easy_event_bus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  screenutil_lego: #@add
  bot_toast_lego: #@add
  widget_binding_lego: #@add
  sa_data_class_lego:
  firebase_core_lego: #@add
  listener_lego:
  sa_firebase_auth_lego:

flutter:
  assets:
    - assets/lego/sa_lego_cloud_functions_lego/
  uses-material-design: true

topics:
  - lego